# Generated by Django 2.2.1 on 2019-05-04 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list',
            field=models.CharField(default='', max_length=255),
        ),
    ]
